import Footer from "@/components/Footer/Footer";
import Header from "@/components/Header/Header";
import { MenuProvider } from "@/Context/MenuContext";
import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Miller Arias Dev",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<MenuProvider>
					<Header />
				</MenuProvider>
				{children}
				<Footer />
			</body>
		</html>
	);
}
