import Header from "@/components/shared/Header/Header";
import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Miller Arias Dev",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<Header />
				<aside>Menu</aside>
				{children}
				<footer>Footer</footer>
			</body>
		</html>
	);
}
